[package]
name = "pancakes"
version = "0.1.0"
authors = ["George Payne <georgepayne@hotmail.com>"]

[dependencies]
hello_macro = { path = "../hello_macro" }
hello_macro_derive = { path = "../hello_macro/hello_macro_derive" }
